# Guardian Interpreter Configuration
# Owner: Blackbox Matrix
# Privacy-first, offline-by-default AI agent

# LLM Configuration
llm:
  # Docker Model Runner (preferred for production)
  docker_runner:
    enabled: true
    api_url: "http://localhost:8080"  # Docker Model Runner API endpoint
    model_name: "guardian-node-llm:v1"  # Model name in Docker registry
    
  # Multiple GGUF Models Configuration (direct loading fallback)
  models:
    default:
      path: "models/phi-3-mini-4k-instruct-q4.gguf"
      context_length: 4096
      temperature: 0.7
      max_tokens: 512
      threads: 4
      age_groups: ["adult", "teen", "child"]
      contexts: ["general", "security", "education", "threat_analysis"]
      description: "General purpose family cybersecurity model"
      
    child_safe:
      path: "models/phi-3-mini-child-safe-q4.gguf"  # Optional specialized model
      context_length: 2048
      temperature: 0.5  # Lower temperature for more consistent child-safe responses
      max_tokens: 256
      threads: 2
      age_groups: ["child"]
      contexts: ["education", "child_safety"]
      description: "Child-safe educational model with strict content filtering"
      
    security_expert:
      path: "models/llama-3.2-3b-security-q4.gguf"  # Optional security-focused model
      context_length: 8192
      temperature: 0.3  # Lower temperature for more precise security analysis
      max_tokens: 1024
      threads: 4
      age_groups: ["adult"]
      contexts: ["security", "threat_analysis", "device_guidance"]
      description: "Security-focused model for detailed threat analysis"
  
  # Legacy single model path (for backward compatibility)
  model_path: "models/your-model.gguf"
  
  # Common LLM settings (used as defaults)
  context_length: 4096
  temperature: 0.7
  max_tokens: 512
  threads: 4  # CPU threads for inference (direct mode only)

# Network Security Settings
network:
  ALLOW_ONLINE: false  # HARD BLOCK internet by default - owner must explicitly enable
  allowed_domains: []  # Whitelist of domains when online is enabled
  log_blocked_calls: true  # Log all blocked outbound requests

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  main_log: "logs/guardian.log"
  blocked_calls_log: "logs/blocked_calls.log"
  max_log_size_mb: 10
  backup_count: 5

# Skills Configuration
skills:
  auto_load: true  # Automatically load all skills from skills/ directory
  skills_directory: "skills"
  allow_system_calls: false  # Restrict skills from making system calls by default

# CLI Configuration
cli:
  prompt_prefix: "Guardian> "
  show_skill_list_on_start: true
  max_history: 100

# Privacy Settings
privacy:
  no_telemetry: true
  no_auto_updates: true
  no_external_apis: true
  audit_all_actions: true

# Family Assistant Configuration
family_assistant:
  enabled: true
  gui_enabled: true
  default_interface: "gui"  # "gui" or "cli"
  family_data_path: "data/families"
  
  # Family-specific LLM settings
  family_llm:
    system_prompt_template: "family_assistant_prompt.txt"
    max_response_length: 1000
    child_safe_mode: true
    default_safety_level: "standard"  # "strict", "moderate", "standard"
    
  # GUI Configuration
  gui:
    theme: "family_friendly"
    font_size: "large"
    high_contrast: false
    touch_interface: true
    screen_timeout: 300  # seconds
    
  # Family Skills Configuration
  family_skills:
    threat_analysis_enabled: true
    device_guidance_enabled: true
    child_education_enabled: true
    auto_recommendations: true
    
  # Performance Settings
  performance:
    cache_responses: true
    cache_size_mb: 50
    background_analysis: false
    priority_family_queries: true
    
  # Voice Interface Configuration
  voice_interface:
    enabled: true
    wake_word: "guardian"
    session_timeout: 30  # seconds
    max_retries: 3
    privacy_mode: true
    require_confirmation: true
    
  # Voice Input Settings
  voice_input:
    timeout: 5  # seconds
    phrase_timeout: 1  # seconds
    energy_threshold: 300
    offline_mode: true
    block_online: true  # Block online speech recognition for privacy
    privacy_mode: true
    log_audio: false
    
  # Voice Output Settings
  voice_output:
    speech_rate: 150  # words per minute
    volume: 0.8  # 0.0 to 1.0
    family_mode: true
    child_friendly_voice: true
    log_speech: false

# Protocol Modules Configuration
protocol_modules:
  enabled: true
  modules_directory: "protocols"
  auto_load_family_protocols: true
  family_friendly_mode: true
  max_analysis_results: 1000

# System Information
system:
  name: "Guardian Interpreter"
  version: "1.0.0"
  owner: "Blackbox Matrix"
  description: "Local Modular AI Agent (Nodie Edition)"

